# pyproject.toml
[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "expo_jbm329"
version = "1.0.0"
description = "Workbench for datapreparation and dataset analysis"
authors = [{name = "Jonas Brännström", email = "jonas.brannstrom@gmail.com"}]
readme = "README.md"
license = "GPL-3.0-or-later"
changelog = "CHANGELOG.md"


requires-python = ">=3.13, <3.14"

classifiers = [
    "Private :: Do Not Upload",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: Qt",
]

# -------------------------------
# Runtime dependencies
# -------------------------------

dependencies = [
    "pyqt6>=6.10.2",
    "sqlalchemy>=2.0.46,<2.0.54",
    "chardet",
    "pyodbc",
    "openpyxl>=3.1.5",
    "platformdirs>=4.9.2",
    "pyarrow>=23.0.1",
    "pandas>=2.3.3",
    "numpy>=2.3.5",
    "pyqt6-sip>=13.11.0",
    "httpx>=0.28.1",
    "pyqvd>=2.3.2",
    "pyreadstat>=1.3.5",
    "sqlglot>=30.12.0",
]

# -------------------------------
# Development-only dependencies
# -------------------------------
[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=4.1",
    "ruff>=0.5",
    "mypy>=1.10",
    "pyinstaller>=6.4",
    "pyside6-essentials>=6.10.2",
    "pandas-stubs>=2.3.3"

]
profiling = [
    "ydata-profiling>=4.18",
    "setuptools>=72.0.0,<80.0.0",
    "matplotlib>=3.10.0",
]


# -------------------------------
# CLI/GUI entry points
# -------------------------------
[project.scripts]
expo-gui = "expo_jbm329.gui_main:gui_main"
expo = "expo_jbm329.cli_main:cli_main"
build-exe = "expo_jbm329.build:build_exe"
build-release = "expo_jbm329.build:build_release"
build-resources = "expo_jbm329.build_resources:main"
build-i18n = "expo_jbm329.build_i18n:main"
build-locales = "expo_jbm329.build_locales:main"

# -------------------------------
# Package-data (ikoner, qrc)
# -------------------------------
[tool.hatch.build]
include = [
    "src/expo_jbm329/workbench/icon/themes/dark/*.png",
    "src/expo_jbm329/workbench/icon/themes/light/*.png",
    "src/expo_jbm329/workbench/icon/*.ico",
    "src/expo_jbm329/workbench/icon/icons.qrc",
    "src/expo_jbm329/workbench/icon/icons_rc.py",
]

# -------------------------------
# Build targets
# -------------------------------
[tool.hatch.build.targets.wheel]
packages = ["src/expo_jbm329"]

[tool.hatch.build.targets.sdist]
include = [
  "src/expo_jbm329/**",
  "pyproject.toml",
  "README.md"
]

# -------------------------------
# Ruff
# -------------------------------
[tool.ruff]
# Allow lines to be as long as 120.
line-length = 120
target-version = "py313"
src = ["src", "tests"]
exclude = [
    ".venv",
    "build/",
    "dist/",
    "hooks/",
    "scripts",
    "tools/",
    "__pycache__/",
    "src/expo_jbm329/workbench/icon/icons_rc.py",
    "src/expo_jbm329/workbench/icon/icons.qrc",
    "src/expo_jbm329/workbench/splash/splash_rc.py",
    "src/expo_jbm329/workbench/splash/splash.qrc",
    "src/expo_jbm329/i18n/locales/*",
]
respect-gitignore = true


[tool.ruff.lint]

select = [
    "B",    # bugbear
    "D",    # docstrings
    "E",    # pycodestyle (errors)
    "F",    # pyflakes
    "G",    # flake8-logging-format
    "I",    # isort
    "N",    # pep8-naming
    "Q",    # quotes consistency
#    "S",    # flake8-bandit
    "W",    # pycodestyle (warnings)
    "UP",   # pyupgrade
    "C90",  # complexity (mccabe)
    "RET",  # return statements
    "SIM",  # simplify
    "ARG",  # unused args
    "RUF",  # Ruff's own rules
    "FURB", # flake8-ruff
    "PLE",  # flake8-pie
    "PLC",  # flake8-pie
    "PD",   # pandas-vet
    "PTH",  # flake8-use-pathlib
    "NPY",  # numpy
    "TC",   # flake8-type-checking
    "TID",  # flake8-tidy-imports
    "SLOT", # flake8-slots
    "SIM",  # flake8-simplify
    "SLF",  # flake8-self
    "PYI",  # flake8-pyi
    "PIE",  # flake8-pie
    "LOG",  # flake8-logging-format
    "ISC",  # flake8-implicit-str-concat
    "INT",  # flake8-interpreted-string
    "FA",   # flake8-future-import
    "EM",   # flake8-errmsg
#    "DTZ",  # flake8-datetimez
    "BLE",  # flake8-blind-except
    "ASYNC",# flake8-async
    "ANN",  # flake8-annotations
    "ERA",  # flake8-eradicate
    "AIR",  # flake8-airflow
]

ignore = [
    "ARG",      # unused callback args are common in PyQt/UI flows
    "C90",      # complexity warnings are intentionally not enforced project-wide
    "FURB171",
    "PLC0415",
]
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["W", "D", "S", "S101", "RUF", "D104", "ARG", "PLC", "N", "SLF", "EM", "BLE", "E501", "ANN", "ERA"]
"__init__.py" = ["D107", "D104"]


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 88
skip-magic-trailing-comma = false
preview = true




# -------------------------------
# Pytest
# -------------------------------
[tool.pytest.ini_options]
minversion = "8.0"
addopts = "--maxfail=1"
testpaths = ["tests"]


# -------------------------------
# Mypy
# -------------------------------
[tool.mypy]
python_version = "3.13"
strict = false
ignore_missing_imports = true
warn_unused_ignores = true
mypy_path = ["src"]






